/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomControls: typeof import('./src/components/MyVideo/components/CustomControls/index.vue')['default']
    FastAddress: typeof import('./src/components/fast-address/index.vue')['default']
    FastDataColumn: typeof import('./src/components/fast-data/fast-data-column/index.vue')['default']
    FastDataLabel: typeof import('./src/components/fast-data/fast-data-label/index.vue')['default']
    FastDataSelect: typeof import('./src/components/fast-data/fast-data-select/index.vue')['default']
    FastDataTable: typeof import('./src/components/fast-data/fast-data-table/index.vue')['default']
    FastDictColumn: typeof import('./src/components/fast-dict/fast-dict-column/index.vue')['default']
    FastDictLabel: typeof import('./src/components/fast-dict/fast-dict-label/index.vue')['default']
    FastDictRadio: typeof import('./src/components/fast-dict/fast-dict-radio/index.vue')['default']
    FastDictSelect: typeof import('./src/components/fast-dict/fast-dict-select/index.vue')['default']
    FastEditor: typeof import('./src/components/fast-editor/index.vue')['default']
    FastIcon: typeof import('./src/components/fast-icon/index.vue')['default']
    FastIconSelect: typeof import('./src/components/fast-icon-select/index.vue')['default']
    FastImagePreview: typeof import('./src/components/fast-image-preview/index.vue')['default']
    FastMarkdown: typeof import('./src/components/fast-markdown/index.vue')['default']
    FastOrgInput: typeof import('./src/components/fast-org/fast-org-input/index.vue')['default']
    FastOrgSelect: typeof import('./src/components/fast-org/fast-org-select/index.vue')['default']
    FastPostInput: typeof import('./src/components/fast-post-input/index.vue')['default']
    FastRoleInput: typeof import('./src/components/fast-role-input/index.vue')['default']
    FastUploadImage: typeof import('./src/components/fast-upload/fast-upload-image/index.vue')['default']
    FastUploadImages: typeof import('./src/components/fast-upload/fast-upload-images/index.vue')['default']
    FastUserDialog: typeof import('./src/components/fast-user/fast-user-dialog/index.vue')['default']
    FastUserInput: typeof import('./src/components/fast-user/fast-user-input/index.vue')['default']
    FetctButton: typeof import('./src/components/fetct-button/index.vue')['default']
    MyVideo: typeof import('./src/components/MyVideo/index.vue')['default']
    PlayRate: typeof import('./src/components/MyVideo/components/CustomControls/PlayRate.vue')['default']
    ProgressBar: typeof import('./src/components/MyVideo/components/CustomControls/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectV2: typeof import('./src/components/select-v2/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanDialog: typeof import('vant/es')['Dialog']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VideoDialog: typeof import('./src/components/video-dialog/index.vue')['default']
    Volume: typeof import('./src/components/MyVideo/components/CustomControls/Volume.vue')['default']
  }
}
